name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependency
      run: sudo apt-get install -y gettext gnome-common libibus-1.0-dev liblua5.3-dev libpinyin13-dev libsqlite3-dev libtool python3 python3-gi sqlite3 uuid-dev
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
